// Code generated by test harness; DO NOT EDIT.
package generatedcode

type FooServer struct{}

// ServeHTTP handles generated traffic.
func (FooServer) ServeHTTPv1() {} // want `doc comment starts with 'ServeHTTP' but symbol is 'ServeHTTPv1' \(possible typo or old name\)`
